### ISSUE TITLE
Data-Dictionary

### ISSUE THREAD

**Issue by fedihamdi** [anthonymiyoro/ParseMessenger#2]
Hey Anthony,

Thank you for the great work you've done here, I was wondering if you please provide the _**Data Dictionary**_ you used in your project. 

Thanks.

**Comment by anthonymiyoro** [comment]
Hello Hamdi,

The data dictionary and the data itself can be found here:
[https://www.kaggle.com/kiva/data-science-for-good-kiva-crowdfunding](https://www.kaggle.com/kiva/data-science-for-good-kiva-crowdfunding)
